Repository The-Bugger-Ducks/owl-partners-mobile, pull requests merged in 2023-05, with the labels that each got.

#77 Fix/hide buttons from meeting details
  src/screens/Home/index.tsx
  src/screens/Meeting/index.tsx
  src/screens/Partnership/MeetingsList/index.tsx
  src/shared/interfaces/meeting.interface.ts
Labels: fix

#79 feat: search user by name
  src/screens/Partnerships/index.tsx
  src/screens/User/index.tsx
  src/shared/constants/endpoints.ts
  src/shared/services/user.request.ts
  src/shared/utils/handlers/formatEnumsPartner.ts
Labels: needs revision, pull request

#82 Hotfix/user update and search user
  src/screens/Home/index.tsx
  src/screens/MyProfile/index.tsx
  src/screens/User/index.tsx
  src/screens/User/styles.ts
  src/shared/services/user.request.ts
Labels: bug
