Repository The-Bugger-Ducks/owl-partners-mobile, pull requests merged in 2023-04, with the labels that each got.

#27 fix #0502 handle error in sign Screen
  src/routes/BottomTabs/index.tsx
  src/screens/Auth/SignIn/index.tsx
  src/shared/services/auth.request.ts
  src/shared/types/rootStackParamList.ts
Labels: bug

#29 fix Image logo in header component
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/shared/assets/logo.png
Labels: bug

#34 Feat/#0109 edit partnership
  .github/ISSUE_TEMPLATE/feature-request.md
  package.json
  src/routes/index.tsx
  src/screens/Partnership/index.tsx
  src/screens/Partnership/styles.ts
  src/screens/PartnershipEdit/index.tsx
  src/screens/PartnershipEdit/styles.ts
  src/screens/PartnershipForm/index.tsx
  src/screens/PartnershipForm/styles.ts
  src/screens/PartnershipInformation/index.tsx
  src/screens/PartnershipInformation/styles.ts
  src/screens/Partnerships/index.tsx
  src/shared/interfaces/partner.interface.ts
  src/shared/services/partner.request.ts
  src/shared/types/rootStackParamList.ts
  src/shared/utils/handlers/PartnershipController.ts
  src/utils/classificationSelectOptions.ts
  src/utils/stateSelectOptions.ts
  src/utils/statusSelectOptions.ts
  yarn.lock
Labels: pull request

#41 Hotfix/storage controler
  .github/ISSUE_TEMPLATE/feature-request.md
  src/shared/interfaces/user.interface.ts
  src/shared/services/auth.request.ts
  src/shared/utils/handlers/AnnotationController.ts
Labels: bug

#43 Fix/#0111 deleted partnerships
  src/components/Card/index.tsx
  src/screens/Partnership/index.tsx
  src/shared/interfaces/annotation.interface.ts
Labels: pull request

#42 Fix/#009 dropdown to select
  package.json
  src/screens/PartnershipEdit/index.tsx
  src/screens/PartnershipEdit/styles.ts
  src/screens/PartnershipForm/index.tsx
  src/screens/PartnershipForm/styles.ts
  src/utils/stateSelectOptions.ts
  yarn.lock
Labels: pull request

#44 Refactor/#0007 icons
  .babelrc
  declarations.d.ts
  metro.config.js
  package.json
  src/components/Icon/icons.tsx
  src/components/Icon/index.tsx
  src/components/index.ts
  src/shared/assets/icons/check.svg
  src/shared/assets/icons/checkbox-off.svg
  src/shared/assets/icons/checkbox-on.svg
  src/shared/assets/icons/close.svg
  src/shared/assets/icons/edit.svg
  src/shared/assets/icons/eye-hidden.svg
  src/shared/assets/icons/eye.svg
  src/shared/assets/icons/home.svg
  src/shared/assets/icons/image.svg
  src/shared/assets/icons/info.svg
  src/shared/assets/icons/loading.svg
  src/shared/assets/icons/log-off.svg
  src/shared/assets/icons/menu.svg
  src/shared/assets/icons/minus.svg
  src/shared/assets/icons/order.svg
  src/shared/assets/icons/plus.svg
  src/shared/assets/icons/profile.svg
  src/shared/assets/icons/question.svg
  src/shared/assets/icons/radio-1.svg
  src/shared/assets/icons/radio.svg
  src/shared/assets/icons/refresh.svg
  src/shared/assets/icons/search.svg
  src/shared/assets/icons/trash.svg
  src/shared/assets/icons/users.svg
  yarn.lock
Labels: needs revision

#47 Feat/#0008 go back button navigation
  package.json
  src/components/Icon/icons.tsx
  src/components/Icons/Info.tsx
  src/routes/CustomHeaderTitle/index.tsx
  src/routes/CustomHeaderTitle/styles.ts
  src/routes/index.tsx
  src/screens/Partnership/AnnotationsList/index.tsx
  src/screens/Partnership/EditPartnershipModal/index.tsx
  src/screens/Partnership/EditPartnershipModal/styles.ts
  src/screens/Partnership/styles.ts
  src/screens/Partnerships/AddPartnershipModal/index.tsx
  src/screens/Partnerships/AddPartnershipModal/styles.ts
  src/shared/assets/icons/arrow-left.svg
  src/shared/constants/validEmailPattern.ts
Labels: feature request, review needed, mobile

#49 Feat/#0612 listing meetings
  src/components/Card/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Partnership/AnnotationsList/index.tsx
  src/screens/Partnership/MeetingsList/index.tsx
  src/screens/Partnership/index.tsx
  src/shared/constants/endpoints.ts
  src/shared/interfaces/meeting.interface.ts
  src/shared/services/meeting.request.ts
Labels: feature request, review needed

#55 Search bar (partnerships)
  src/screens/Partnerships/index.tsx
  src/shared/constants/endpoints.ts
  src/shared/services/partnership.requests.ts
  src/shared/utils/alertError.ts
Labels: pull request

#71 Fix/can edit logic
  src/components/Card/index.tsx
  src/screens/Partnership/AnnotationsList/index.tsx
  src/screens/Partnership/MeetingsList/index.tsx
  src/screens/Partnership/index.tsx
  src/shared/services/partnership.requests.ts
Labels: fix
