Repository The-Bugger-Ducks/owl-partners-mobile, pull requests merged in 2023-06, with the labels that each got.

#84 Fix/#0024 component icons
  src/components/Card/index.tsx
  src/components/Icon/index.tsx
  src/components/Input/index.tsx
  src/components/Modal/index.tsx
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignUp/index.tsx
  src/screens/Home/index.tsx
  src/screens/User/index.tsx
Labels: fix

#86 Feat/#0409 permission management
  src/components/Text/index.tsx
  src/screens/Auth/SignUp/index.tsx
  src/screens/Home/index.tsx
  src/screens/User/index.tsx
  src/screens/User/styles.ts
  src/shared/interfaces/user.interface.ts
  src/shared/services/user.request.ts
Labels: feature request

#87 Feat/#83 0115 filtragem das parcerias por status
  src/components/Icon/icons.tsx
  src/components/Input/index.tsx
  src/screens/Partnerships/FilterPartnershipModal/index.tsx
  src/screens/Partnerships/FilterPartnershipModal/styles.ts
  src/screens/Partnerships/index.tsx
  src/screens/Partnerships/styles.ts
  src/screens/User/index.tsx
  src/shared/assets/icons/circle.svg
  src/shared/assets/icons/filter.svg
  src/shared/assets/icons/list-layout.svg
  src/shared/services/partnership.requests.ts
  src/shared/services/user.request.ts
Labels: enhancement

#88 Development
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Card/index.tsx
  src/components/Header/styles.ts
  src/components/Icon/icons.tsx
  src/components/Icon/index.tsx
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/components/Modal/index.tsx
  src/components/Text/index.tsx
  src/routes/index.tsx
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignUp/index.tsx
  src/screens/Auth/SignUp/styles.ts
  src/screens/Home/AddMeetingModal/index.tsx
  src/screens/Home/index.tsx
  src/screens/Meeting/AnnotationsList/index.tsx
  src/screens/Meeting/index.tsx
  src/screens/Meeting/styles.ts
  src/screens/MyProfile/index.tsx
  src/screens/MyProfile/styles.ts
  src/screens/Partnership/AnnotationsList/index.tsx
  src/screens/Partnership/MeetingsList/index.tsx
  src/screens/Partnership/index.tsx
  src/screens/Partnership/styles.ts
  src/screens/Partnerships/FilterPartnershipModal/index.tsx
  src/screens/Partnerships/FilterPartnershipModal/styles.ts
  src/screens/Partnerships/index.tsx
  src/screens/Partnerships/styles.ts
  src/screens/User/index.tsx
  src/screens/Users/index.tsx
  src/screens/Users/styles.ts
  src/shared/assets/icons/circle.svg
  src/shared/assets/icons/filter.svg
  src/shared/assets/icons/list-layout.svg
  src/shared/interfaces/user.interface.ts
  src/shared/services/partnership.requests.ts
  src/shared/services/user.request.ts
  src/shared/types/rootStackParamList.ts
  src/shared/utils/checkUserAdmin.ts
  src/shared/utils/useThrottle.ts
Labels: mobile
